# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelnest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
